### ISSUE TITLE
This error appear

### ISSUE THREAD

**Issue by kevincrafturu2** [justacoincidence/Discord-QR-Grabber-Bot#3]
![image](https://user-images.githubusercontent.com/48927699/187087814-5b848d6f-9301-415b-aa12-9e7e100332f5.png)

**Comment by kevincrafturu2** [comment]
There is that error when i use replit

**Comment by kevincrafturu2** [comment]
Hi?

**Comment by D3strcutive** [comment]
> ![image](https://user-images.githubusercontent.com/48927699/187087814-5b848d6f-9301-415b-aa12-9e7e100332f5.png)
go to shell and write: pip install selenium.webdriver.chrome.options

**Comment by justacoincidence** [comment]
Don't care the only reason you would be spinning up this project and having problems is your a wannabe blackhat skid that doesn't know how to do anything and you're trying to use the bot for malicous purposes.
